services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "3001:3001"

  rating-service:
    build: ./services/rating-service
    env_file:
      - ./services/rating-service/.env
    depends_on:
      - mongodb
    ports:
      - "3002:3002"

  game-lifecycle-service:
    build: ./services/game-lifecycle-service
    env_file:
      - ./services/game-lifecycle-service/.env
    depends_on:
      - redis
    ports:
      - "3003:3003"

  matchmaking-service:
    build: ./services/matchmaking-service
    env_file:
      - ./services/matchmaking-service/.env
    depends_on:
      - redis
    ports:
      - "3004:3004"

  game-history-service:
    build: ./services/game-history-service
    env_file:
      - ./services/game-history-service/.env
    depends_on:
      - mongodb
    ports:
      - "3005:3005"

  websocket-gateway-service:
    build: ./services/websocket-gateway-service
    env_file:
      - ./services/websocket-gateway-service/.env
    depends_on:
      - redis
    ports:
      - "3006:3006"

  frontend:
    build: ./client
    ports:
      - "5173:80"

volumes:
  mongo-data:
